import type { Metadata } from "next"
import "./globals.css"

// Fonts
import { Azeret_Mono, Anton, Barlow_Condensed } from "next/font/google"

const AzeretMonoFont = Azeret_Mono({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-azeret-mono",
})

const AntonFont = Anton({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-anton",
})

const BarlowCondensedFont = Barlow_Condensed({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-barlow",
})

export const metadata: Metadata = {
	title: "BLITZWERK",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`${AzeretMonoFont.variable} ${AntonFont.variable} ${BarlowCondensedFont.variable} antialiased`}
		>
			<body>{children}</body>
		</html>
	)
}
